<script lang="ts" context="module">
	export const name = 'advanced-usage';
	export const title = 'Advanced usage';
</script>

<script lang="ts">
	import Prism from 'prismjs';
	import { CodeSnippet } from 'carbon-components-svelte';
	import HighlightCodeSnippet from '$lib/components/HighlightCodeSnippet.svelte';

	const initializeTypeCode = `
export type InitInput =
  | RequestInfo
  | URL
  | Response
  | BufferSource
  | WebAssembly.Module;
export const initialize: (mod: Promise<InitInput> | InitInput) => Promise<void>;`.trim();

	const initializeExampleCode = `
// full code (WebAsembly.Module)
const response = await fetch('https://unpkg.com/svg2png-wasm/svg2png_wasm_bg.wasm');
const buffer = await response.arrayBuffer();
const { module } = await WebAssembly.instantiate(buffer);
await initialize(module);

// BufferSource
const response = await fetch('https://unpkg.com/svg2png-wasm/svg2png_wasm_bg.wasm');
const buffer = await response.arrayBuffer();
await initialize(buffer);

// Response
const response = await fetch('https://unpkg.com/svg2png-wasm/svg2png_wasm_bg.wasm');
await initialize(response);

// Promise<Response>
await initialize(fetch('https://unpkg.com/svg2png-wasm/svg2png_wasm_bg.wasm'));

// in Deno (Promise<BufferSource>)
await initialize(Deno.readFile('./svg2png_wasm_bg.wasm'));

// in Deno and Browser (RequestInfo (=string/URL))
await initialize('https://unpkg.com/svg2png-wasm/svg2png_wasm_bg.wasm');`.trim();

	const createSvg2pngCode = `
const svgs = [
  '<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"> ... </svg>',
  '<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"> ... </svg>',
  '<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"> ... </svg>',
  // and more ...
];
const font = await fetch('./Roboto.ttf').then((res) => res.arrayBuffer());
const svg2png = createSvg2png({
  fonts: [new Uint8Array(font)],
});

const pngs = await Promise.all(svgs.map((svg) => svg2png(svg, { scale: 2 })));
svg2png.dispose(); // You should dispose svg2png, if you will not use it in the future
`.trim();
</script>

<h3>Initialize only once</h3>
<p>
	The <CodeSnippet type="inline" code="initialize" /> function can be called only
	once.
</p>
<p>
	If it is called more than once,
	<CodeSnippet type="inline" code="Promise" /> will be rejected.
</p>

<HighlightCodeSnippet
	code={`await initialize(wasm).catch((e) => { /* Called twice (OR Invalid wasm module) */ });`}
	grammar={Prism.languages.js}
	language="javascript"
/>

<h3>Initialize without buffer</h3>
<p>
	The argument of the <CodeSnippet type="inline" code="initialize" /> function can
	be something other than a buffer.
</p>

<h4>Types</h4>
<HighlightCodeSnippet
	type="multi"
	code={initializeTypeCode}
	grammar={Prism.languages.js}
	language="typescript"
/>

<h4>Examples</h4>
<HighlightCodeSnippet
	type="multi"
	code={initializeExampleCode}
	grammar={Prism.languages.js}
	language="javascript"
/>

<h3>Custom svg2png</h3>
<p>You can create a custom svg2png function.</p>

<p>
	Basically, you can use
	<CodeSnippet type="inline" code="svg2png" />, but if you want to process a lot
	of data continuously, consider using
	<CodeSnippet type="inline" code="createSvg2png" />. It can reduce the overhead
	of font loading. Converters generated by
	<CodeSnippet type="inline" code="createSvg2png" />
	should be disposed of after use by calling the dispose method.
</p>

<HighlightCodeSnippet
	type="multi"
	code={createSvg2pngCode}
	grammar={Prism.languages.js}
	language="javascript"
/>

<style>
	h3,
	h4,
	p {
		padding-top: 0.5em;
	}
</style>
